import React from "react";
import { Providers } from "./Providers";
import type { Metadata } from "next";
import NavBar from "./components/NavBar";
import DemoBanner from "./components/DemoBanner";
import Footer from "./components/Footer";
import "./globals.css";
import "../styles/overrides/portable.css";

export const metadata: Metadata = {
  title: "Practical next ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <header>
            <NavBar />
            <DemoBanner />
          </header>
          <div className="layout">
            <main className="main-container">{children}</main>
            <footer>
              <Footer />
            </footer>
          </div>
        </Providers>
      </body>
    </html>
  );
}
