import React from "react";
import { Toaster } from "react-hot-toast";
import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/NavBar";
import DemoBanner from "./components/DemoBanner";

export const metadata: Metadata = {
  title: "Limitless",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <NavBar />
          <DemoBanner />
        </header>
        <div className="layout">
          <main className="main-container">{children}</main>
          <footer>{/* <Footer /> */}</footer>
        </div>
      </body>
    </html>
  );
}
